default:
  image: node:lts

pages:
  stage: deploy
  script:
    - mv src public
  artifacts:
    paths:
      - public
  only:
    - master

ipfs:
  stage: deploy
  script:
  - pwd
  - ls -a
  - ls -a src
  - npm i -g @jych/pin-to-ipfs
  - cd src
  - pin-to-ipfs --key=$PINATA_API_KEY --secret=$PINATA_API_SECRET --dir=$(pwd)
