name: Deploy to GitHub Pages & IPFS
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4 # pnpm version is read from package.json

      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: "pnpm run build:prod"

      - name: Remove Template Files
        run: rm -rf src/data.json src/index.mustache

      - name: Move Output to Dist
        run: mv src dist

      - uses: actions/upload-artifact@v4
        with:
          name: build-dist
          path: dist
          retention-days: 1

  deploy-gh-pages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: actions/download-artifact@v4
        with:
          name: build-dist
          path: dist

      - name: Deploy to GH Pages 🚀
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ github.token }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: dist # The folder the action should deploy.
          CLEAN: true # Automatically remove deleted files from the deploy branch.
