name: Deploy to GitHub Pages & IPFS
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Install pnpm
        uses: pnpm/action-setup@v4 # pnpm version is read from package.json

      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: "pnpm run build:prod"

      - name: Remove Template Files
        run: rm -rf src/data.json src/index.mustache

      - name: Deploy to GH Pages 🚀
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: src # The folder the action should deploy.
          CLEAN: true # Automatically remove deleted files from the deploy branch.

      - name: Pin to IPFS 🚀
        id: pin
        uses: jamescallumyoung/pinata-publish-action@v0.1.1
        with:
          pinata-api-key: ${{ secrets.PINATA_API_KEY }}
          pinata-secret-api-key: ${{ secrets.PINATA_API_SECRET }}
          file-to-pin: src # Pin the whole src dir

      - name: Get the IPFS pinned hash
        run: echo "The hash of the pin is ${{ steps.pin.outputs.hash }}"

      - name: Update DNSLink
        uses: decooio/cloudflare-dnslink-action@v1.0.0
        with:
          name: ${{ secrets.IPNS_DOMAIN_NAME }}
          cid: ${{ steps.pin.outputs.hash }}
          token: ${{ secrets.CLOUDFLARE_TOKEN }}
          zone: ${{ secrets.CLOUDFLARE_ZONE_ID }}
