# This action requires the following secrets to be set:
#   github.token - set by GH
#   STORACHA_KEY - created by `w3 key create --json`
#   STORACHA_PROOF - created by `w3 delegation create --base64`

name: Deploy to GitHub Pages & IPFS
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Install pnpm
        uses: pnpm/action-setup@v4 # pnpm version is read from package.json

      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: "pnpm run build:prod"

      - name: Remove Template Files
        run: rm -rf src/data.json src/index.mustache

      - name: Move Output to Dist
        run: mv src dist

      - uses: actions/upload-artifact@v4
        with:
          name: build-dist
          path: dist
          retention-days: 1

  deploy-gh-pages:
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - uses: actions/download-artifact@v4
        with:
          name: build-dist
          path: dist

      - name: Deploy to GH Pages 🚀
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ github.token }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: dist # The folder the action should deploy.
          CLEAN: true # Automatically remove deleted files from the deploy branch.

  deploy-ipfs:
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - uses: actions/download-artifact@v4
        with:
          name: build-dist
          path: dist

      - name: Deploy to IPFS
        id: deploy
        uses: ipfs/ipfs-deploy-action@v1
        with:
          path-to-deploy: dist
          storacha-key: ${{ secrets.STORACHA_KEY }}
          storacha-proof: ${{ secrets.STORACHA_PROOF }}
          github-token: ${{ github.token }}
